server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userCircuitBreaker
                fallbackUri: forward:/fallback/userCircuitBreaker
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
              - Path=/dept/**
          filters:
            - name: CircuitBreaker
              args:
                name: deptCircuitBreaker
                fallbackUri: forward:/fallback/deptCircuitBreaker
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 90
    hostname: localhost
#    hostname: DESKTOP-PGJNFJ5
    prefer-ip-address: true
    ip-address: 127.0.0.1
management:
  endpoints:
    web:
      exposure:
        include: ['*','circuitbreakers']

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
    instances:
      userCircuitBreaker:
        base-config: default
      deptCircuitBreaker:
        base-config: default
logging:
  level:
#    org.springframework.cloud.commons.util.InetUtils: trace
    org.springframework.cloud.gateway.filter.GatewayFilter: debug
    org.springframework.cloud.gateway: debug
    io.github.resilience4j: debug



